### ISSUE TITLE
Notes in Drafts

### ISSUE THREAD

**Issue by masonry47** [ethercreative/notes#4]
Hi there!

We noticed that the notes field does not seem to work with the draft workflow in Craft.  

Here are the steps to reproduce:

Create a new draft for an Entry containing a "Notes" field.
Refresh the page OR switch to a different site via the dropdown.
See issue; existing Notes disappear from the Draft.
Add a new Note to the Draft and publish it.
See issue; Notes added to the Draft aren't added to the Entry.

Craft CMS 3.5.18
Notes 1.0.4

Thanks in advance!

**Comment by alexjcollins** [comment]
Thanks for flagging, we'll check this out!

**Comment by masonry47** [comment]
Thanks for this!  We are still seeing the second half of our issue.  When adding notes to the draft they do not seem to save.  Thanks again!
