### ISSUE TITLE
Suspending or Deleting author creates undefined offset error and takes site down

### ISSUE THREAD

**Issue by matthewmrotter** [ethercreative/notes#5]
When a user is suspended it creates an undefined offset causing the site to break: 

Undefined offset: 10315 in /home/234685.cloudwaysapps.com/kmhyedxrux/public_html/vendor/ether/notes/src/Service.php:96 Stack trace: #0 /home/234685.cloudwaysapps.com/kmhyedxrux/public_html/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError() #1 /home/234685.cloudwaysapps.com/kmhyedxrux/public_html/vendor/ether/notes/src/Service.php(96): craft\web\ErrorHandler->handleError()

Craft version: 3.7.10
Plugin version: 1.0.5

**Comment by masonry47** [comment]
Hi there, 

We are having the same issue.  When trying to edit an entry for a section using the the Notes field in which a suspended user made a not we get this. 

![Screen Shot 2021-12-29 at 8 48 17 AM](https://user-images.githubusercontent.com/48130527/147674434-3b5cf704-72ec-41c9-93ff-283f3a1f15da.png)

We know we can change line 96 to something like this

`'author' => $users[$note['userId']] ?? null`

But we are hoping you can put in something more permanent.  

Thanks in advance!

**Comment by alexjcollins** [comment]
Hey,

Sorry for the delay in responding to the original issue and thanks for the additional information in the latest comment.

We'll get this looked at next week.
