### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by jamiepittock** [ethercreative/notes#6]
Will this plugin be upgraded for Craft 4?

**Comment by jamiepittock** [comment]
Hi, have you decided yet whether this plugin will be upgraded for Craft 4?

**Comment by masonry47** [comment]
+1

**Comment by andrewhawkes** [comment]
I know this is quite old now - but can you confirm if there's any chance of this being updated

**Comment by alexjcollins** [comment]
Hey everyone. This _will_ be updated, but I'm not 100% sure when. It was built for a client who is still on Craft 3 and we're planning the move to 5 (decided to 'skip' 4). I'll make sure I update this issue when we're gearing up to migrate (hopefully in the next few months).

**Comment by andrewhawkes** [comment]
> Hey everyone. This _will_ be updated, but I'm not 100% sure when. It was built for a client who is still on Craft 3 and we're planning the move to 5 (decided to 'skip' 4). I'll make sure I update this issue when we're gearing up to migrate (hopefully in the next few months).

Thanks - in the process of taking a site from 3 to 5 via 4 ha and they used this a fair bit and it's ideal.
Otherwise we'll have to come up with something else.

**Comment by andrewhawkes** [comment]
@alexjcollins Just FYI - as you're updating this and we have a lot of usage of the plugin on a site we need to upgrade, I've just manually updated the plugin for this one site using [craftcms/rector ](https://github.com/craftcms/rector) and it's working as expected.

**Comment by Tam** [comment]
Just released for Craft 4 & 5
